include: package:lints/recommended.yaml

analyzer:
linter:
  rules:
    - always_declare_return_types
    - directives_ordering
    - no_adjacent_strings_in_list
    - package_api_docs
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
