include: package:pedantic/analysis_options.1.9.0.yaml

analyzer:
linter:
  rules:
    #- always_declare_return_types
    #- annotate_overrides
    - avoid_init_to_null
    - directives_ordering
    - no_adjacent_strings_in_list
    - package_api_docs
    - prefer_final_fields
    - slash_for_doc_comments
