name: Dart

on:
  schedule:
    # “At 00:00 (UTC) on Sunday.”
    - cron: '0 0 * * 0'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  analyze-code:
    name: Static analysis (Code)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        persist-credentials: false
    - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260
    - run: dart --version
    - run: dart pub get
    - run: dart analyze --fatal-infos --fatal-warnings .

  analyze-ci:
    name: Static analysis (GitHub Actions)
    runs-on: ubuntu-latest
    # Required by upload-sarif
    permissions:
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7

  format:
    name: Code formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        persist-credentials: false
    - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260
    - run: dart --version
    - run: dart pub get
    - run: dart fix --apply
    - run: dart format .
    - run: git diff --exit-code

  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [3.1, stable, beta]
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        persist-credentials: false
    - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260
      with:
        sdk: ${{ matrix.sdk }}
    - run: dart pub get
    - run: dart pub run test
