name: Dart

on:
  schedule:
    # “At 00:00 (UTC) on Sunday.”
    - cron: '0 0 * * 0'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  analyze-code:
    name: Static analysis (Code)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        persist-credentials: false
    - uses: dart-lang/setup-dart@6afc89df92d6eb3834022f73cd65adc8cdfcb92d
    - run: dart --version
    - run: dart pub get
    - run: dart analyze --fatal-infos --fatal-warnings .

  analyze-ci:
    name: Static analysis (GitHub Actions)
    runs-on: ubuntu-latest
    # Required by upload-sarif
    permissions:
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: zizmorcore/zizmor-action@cc914d7f3750a2d13d75c7f184a1060aa0e9d482 # v0.6.4

  format:
    name: Code formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        persist-credentials: false
    - uses: dart-lang/setup-dart@6afc89df92d6eb3834022f73cd65adc8cdfcb92d
    - run: dart --version
    - run: dart pub get
    - run: dart fix --apply
    - run: dart format .
    - run: git diff --exit-code

  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [3.8, stable, beta]
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        persist-credentials: false
    - uses: dart-lang/setup-dart@6afc89df92d6eb3834022f73cd65adc8cdfcb92d
      with:
        sdk: ${{ matrix.sdk }}
    - run: dart pub get
    - run: dart pub run test
